# docker container for local mysql database.
# database url: mysql://klipse:klipse@localhost:3306/klipse

services:
  mysql:
    image: mysql:8.0
    container_name: klipse
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: klipse
      MYSQL_DATABASE: klipse
      MYSQL_USER: klipse
      MYSQL_PASSWORD: klipse
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
