/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiCronTriggerScheduledJobsRouteImport } from './routes/api/cron/trigger-scheduled-jobs'
import { Route as ApiCronPurgeExpiringAssetsRouteImport } from './routes/api/cron/purge-expiring-assets'
import { Route as ApiCronDispatchQueuedJobsRouteImport } from './routes/api/cron/dispatch-queued-jobs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedDashboardSettingsRouteImport } from './routes/_authed/dashboard/settings'
import { Route as AuthedDashboardPublishingRouteImport } from './routes/_authed/dashboard/publishing'
import { Route as AuthedDashboardJobsRouteImport } from './routes/_authed/dashboard/jobs'
import { Route as AuthedDashboardGenerateRouteImport } from './routes/_authed/dashboard/generate'
import { Route as AuthedDashboardBillingRouteImport } from './routes/_authed/dashboard/billing'
import { Route as AuthedDashboardAnalyticsRouteImport } from './routes/_authed/dashboard/analytics'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminSystemRouteImport } from './routes/_authed/admin/system'
import { Route as AuthedAdminSettingsRouteImport } from './routes/_authed/admin/settings'
import { Route as AuthedAdminKeysRouteImport } from './routes/_authed/admin/keys'
import { Route as AuthedAdminJobsRouteImport } from './routes/_authed/admin/jobs'
import { Route as AuthedDashboardPublishingIndexRouteImport } from './routes/_authed/dashboard/publishing.index'
import { Route as ApiYoutubeOauthStartRouteImport } from './routes/api/youtube/oauth/start'
import { Route as ApiYoutubeOauthCallbackRouteImport } from './routes/api/youtube/oauth/callback'
import { Route as ApiInternalVideoProcessorAssemblyCompleteRouteImport } from './routes/api/internal/video-processor/assembly-complete'
import { Route as ApiInternalProcessorProgressRouteImport } from './routes/api/internal/processor/progress'
import { Route as ApiInternalProcessorKeyFailureRouteImport } from './routes/api/internal/processor/key-failure'
import { Route as AuthedDashboardPublishingDestinationIdRouteImport } from './routes/_authed/dashboard/publishing.$destinationId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const ApiCronTriggerScheduledJobsRoute =
  ApiCronTriggerScheduledJobsRouteImport.update({
    id: '/api/cron/trigger-scheduled-jobs',
    path: '/api/cron/trigger-scheduled-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronPurgeExpiringAssetsRoute =
  ApiCronPurgeExpiringAssetsRouteImport.update({
    id: '/api/cron/purge-expiring-assets',
    path: '/api/cron/purge-expiring-assets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronDispatchQueuedJobsRoute =
  ApiCronDispatchQueuedJobsRouteImport.update({
    id: '/api/cron/dispatch-queued-jobs',
    path: '/api/cron/dispatch-queued-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardSettingsRoute = AuthedDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardPublishingRoute =
  AuthedDashboardPublishingRouteImport.update({
    id: '/publishing',
    path: '/publishing',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardJobsRoute = AuthedDashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardGenerateRoute = AuthedDashboardGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardBillingRoute = AuthedDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardAnalyticsRoute =
  AuthedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminSystemRoute = AuthedAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminSettingsRoute = AuthedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminKeysRoute = AuthedAdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminJobsRoute = AuthedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedDashboardPublishingIndexRoute =
  AuthedDashboardPublishingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardPublishingRoute,
  } as any)
const ApiYoutubeOauthStartRoute = ApiYoutubeOauthStartRouteImport.update({
  id: '/api/youtube/oauth/start',
  path: '/api/youtube/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeOauthCallbackRoute = ApiYoutubeOauthCallbackRouteImport.update({
  id: '/api/youtube/oauth/callback',
  path: '/api/youtube/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalVideoProcessorAssemblyCompleteRoute =
  ApiInternalVideoProcessorAssemblyCompleteRouteImport.update({
    id: '/api/internal/video-processor/assembly-complete',
    path: '/api/internal/video-processor/assembly-complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalProcessorProgressRoute =
  ApiInternalProcessorProgressRouteImport.update({
    id: '/api/internal/processor/progress',
    path: '/api/internal/processor/progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalProcessorKeyFailureRoute =
  ApiInternalProcessorKeyFailureRouteImport.update({
    id: '/api/internal/processor/key-failure',
    path: '/api/internal/processor/key-failure',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedDashboardPublishingDestinationIdRoute =
  AuthedDashboardPublishingDestinationIdRouteImport.update({
    id: '/$destinationId',
    path: '/$destinationId',
    getParentRoute: () => AuthedDashboardPublishingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/admin/jobs': typeof AuthedAdminJobsRoute
  '/admin/keys': typeof AuthedAdminKeysRoute
  '/admin/settings': typeof AuthedAdminSettingsRoute
  '/admin/system': typeof AuthedAdminSystemRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/dashboard/analytics': typeof AuthedDashboardAnalyticsRoute
  '/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/dashboard/generate': typeof AuthedDashboardGenerateRoute
  '/dashboard/jobs': typeof AuthedDashboardJobsRoute
  '/dashboard/publishing': typeof AuthedDashboardPublishingRouteWithChildren
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/dispatch-queued-jobs': typeof ApiCronDispatchQueuedJobsRoute
  '/api/cron/purge-expiring-assets': typeof ApiCronPurgeExpiringAssetsRoute
  '/api/cron/trigger-scheduled-jobs': typeof ApiCronTriggerScheduledJobsRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/publishing/$destinationId': typeof AuthedDashboardPublishingDestinationIdRoute
  '/api/internal/processor/key-failure': typeof ApiInternalProcessorKeyFailureRoute
  '/api/internal/processor/progress': typeof ApiInternalProcessorProgressRoute
  '/api/internal/video-processor/assembly-complete': typeof ApiInternalVideoProcessorAssemblyCompleteRoute
  '/api/youtube/oauth/callback': typeof ApiYoutubeOauthCallbackRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
  '/dashboard/publishing/': typeof AuthedDashboardPublishingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/jobs': typeof AuthedAdminJobsRoute
  '/admin/keys': typeof AuthedAdminKeysRoute
  '/admin/settings': typeof AuthedAdminSettingsRoute
  '/admin/system': typeof AuthedAdminSystemRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/dashboard/analytics': typeof AuthedDashboardAnalyticsRoute
  '/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/dashboard/generate': typeof AuthedDashboardGenerateRoute
  '/dashboard/jobs': typeof AuthedDashboardJobsRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/dispatch-queued-jobs': typeof ApiCronDispatchQueuedJobsRoute
  '/api/cron/purge-expiring-assets': typeof ApiCronPurgeExpiringAssetsRoute
  '/api/cron/trigger-scheduled-jobs': typeof ApiCronTriggerScheduledJobsRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/publishing/$destinationId': typeof AuthedDashboardPublishingDestinationIdRoute
  '/api/internal/processor/key-failure': typeof ApiInternalProcessorKeyFailureRoute
  '/api/internal/processor/progress': typeof ApiInternalProcessorProgressRoute
  '/api/internal/video-processor/assembly-complete': typeof ApiInternalVideoProcessorAssemblyCompleteRoute
  '/api/youtube/oauth/callback': typeof ApiYoutubeOauthCallbackRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
  '/dashboard/publishing': typeof AuthedDashboardPublishingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/_authed/admin/jobs': typeof AuthedAdminJobsRoute
  '/_authed/admin/keys': typeof AuthedAdminKeysRoute
  '/_authed/admin/settings': typeof AuthedAdminSettingsRoute
  '/_authed/admin/system': typeof AuthedAdminSystemRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/dashboard/analytics': typeof AuthedDashboardAnalyticsRoute
  '/_authed/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/_authed/dashboard/generate': typeof AuthedDashboardGenerateRoute
  '/_authed/dashboard/jobs': typeof AuthedDashboardJobsRoute
  '/_authed/dashboard/publishing': typeof AuthedDashboardPublishingRouteWithChildren
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/dispatch-queued-jobs': typeof ApiCronDispatchQueuedJobsRoute
  '/api/cron/purge-expiring-assets': typeof ApiCronPurgeExpiringAssetsRoute
  '/api/cron/trigger-scheduled-jobs': typeof ApiCronTriggerScheduledJobsRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/publishing/$destinationId': typeof AuthedDashboardPublishingDestinationIdRoute
  '/api/internal/processor/key-failure': typeof ApiInternalProcessorKeyFailureRoute
  '/api/internal/processor/progress': typeof ApiInternalProcessorProgressRoute
  '/api/internal/video-processor/assembly-complete': typeof ApiInternalVideoProcessorAssemblyCompleteRoute
  '/api/youtube/oauth/callback': typeof ApiYoutubeOauthCallbackRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
  '/_authed/dashboard/publishing/': typeof AuthedDashboardPublishingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/refund'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/admin/jobs'
    | '/admin/keys'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/users'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/generate'
    | '/dashboard/jobs'
    | '/dashboard/publishing'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/cron/dispatch-queued-jobs'
    | '/api/cron/purge-expiring-assets'
    | '/api/cron/trigger-scheduled-jobs'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/publishing/$destinationId'
    | '/api/internal/processor/key-failure'
    | '/api/internal/processor/progress'
    | '/api/internal/video-processor/assembly-complete'
    | '/api/youtube/oauth/callback'
    | '/api/youtube/oauth/start'
    | '/dashboard/publishing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/refund'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/jobs'
    | '/admin/keys'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/users'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/generate'
    | '/dashboard/jobs'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/cron/dispatch-queued-jobs'
    | '/api/cron/purge-expiring-assets'
    | '/api/cron/trigger-scheduled-jobs'
    | '/admin'
    | '/dashboard'
    | '/dashboard/publishing/$destinationId'
    | '/api/internal/processor/key-failure'
    | '/api/internal/processor/progress'
    | '/api/internal/video-processor/assembly-complete'
    | '/api/youtube/oauth/callback'
    | '/api/youtube/oauth/start'
    | '/dashboard/publishing'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/privacy'
    | '/refund'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/_authed/admin'
    | '/_authed/dashboard'
    | '/_authed/admin/jobs'
    | '/_authed/admin/keys'
    | '/_authed/admin/settings'
    | '/_authed/admin/system'
    | '/_authed/admin/users'
    | '/_authed/dashboard/analytics'
    | '/_authed/dashboard/billing'
    | '/_authed/dashboard/generate'
    | '/_authed/dashboard/jobs'
    | '/_authed/dashboard/publishing'
    | '/_authed/dashboard/settings'
    | '/api/auth/$'
    | '/api/cron/dispatch-queued-jobs'
    | '/api/cron/purge-expiring-assets'
    | '/api/cron/trigger-scheduled-jobs'
    | '/_authed/admin/'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/publishing/$destinationId'
    | '/api/internal/processor/key-failure'
    | '/api/internal/processor/progress'
    | '/api/internal/video-processor/assembly-complete'
    | '/api/youtube/oauth/callback'
    | '/api/youtube/oauth/start'
    | '/_authed/dashboard/publishing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDispatchQueuedJobsRoute: typeof ApiCronDispatchQueuedJobsRoute
  ApiCronPurgeExpiringAssetsRoute: typeof ApiCronPurgeExpiringAssetsRoute
  ApiCronTriggerScheduledJobsRoute: typeof ApiCronTriggerScheduledJobsRoute
  ApiInternalProcessorKeyFailureRoute: typeof ApiInternalProcessorKeyFailureRoute
  ApiInternalProcessorProgressRoute: typeof ApiInternalProcessorProgressRoute
  ApiInternalVideoProcessorAssemblyCompleteRoute: typeof ApiInternalVideoProcessorAssemblyCompleteRoute
  ApiYoutubeOauthCallbackRoute: typeof ApiYoutubeOauthCallbackRoute
  ApiYoutubeOauthStartRoute: typeof ApiYoutubeOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/api/cron/trigger-scheduled-jobs': {
      id: '/api/cron/trigger-scheduled-jobs'
      path: '/api/cron/trigger-scheduled-jobs'
      fullPath: '/api/cron/trigger-scheduled-jobs'
      preLoaderRoute: typeof ApiCronTriggerScheduledJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/purge-expiring-assets': {
      id: '/api/cron/purge-expiring-assets'
      path: '/api/cron/purge-expiring-assets'
      fullPath: '/api/cron/purge-expiring-assets'
      preLoaderRoute: typeof ApiCronPurgeExpiringAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/dispatch-queued-jobs': {
      id: '/api/cron/dispatch-queued-jobs'
      path: '/api/cron/dispatch-queued-jobs'
      fullPath: '/api/cron/dispatch-queued-jobs'
      preLoaderRoute: typeof ApiCronDispatchQueuedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/publishing': {
      id: '/_authed/dashboard/publishing'
      path: '/publishing'
      fullPath: '/dashboard/publishing'
      preLoaderRoute: typeof AuthedDashboardPublishingRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/jobs': {
      id: '/_authed/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof AuthedDashboardJobsRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/generate': {
      id: '/_authed/dashboard/generate'
      path: '/generate'
      fullPath: '/dashboard/generate'
      preLoaderRoute: typeof AuthedDashboardGenerateRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/billing': {
      id: '/_authed/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthedDashboardBillingRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/analytics': {
      id: '/_authed/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/system': {
      id: '/_authed/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthedAdminSystemRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/settings': {
      id: '/_authed/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthedAdminSettingsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/keys': {
      id: '/_authed/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AuthedAdminKeysRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/jobs': {
      id: '/_authed/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthedAdminJobsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/dashboard/publishing/': {
      id: '/_authed/dashboard/publishing/'
      path: '/'
      fullPath: '/dashboard/publishing/'
      preLoaderRoute: typeof AuthedDashboardPublishingIndexRouteImport
      parentRoute: typeof AuthedDashboardPublishingRoute
    }
    '/api/youtube/oauth/start': {
      id: '/api/youtube/oauth/start'
      path: '/api/youtube/oauth/start'
      fullPath: '/api/youtube/oauth/start'
      preLoaderRoute: typeof ApiYoutubeOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/oauth/callback': {
      id: '/api/youtube/oauth/callback'
      path: '/api/youtube/oauth/callback'
      fullPath: '/api/youtube/oauth/callback'
      preLoaderRoute: typeof ApiYoutubeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/video-processor/assembly-complete': {
      id: '/api/internal/video-processor/assembly-complete'
      path: '/api/internal/video-processor/assembly-complete'
      fullPath: '/api/internal/video-processor/assembly-complete'
      preLoaderRoute: typeof ApiInternalVideoProcessorAssemblyCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/processor/progress': {
      id: '/api/internal/processor/progress'
      path: '/api/internal/processor/progress'
      fullPath: '/api/internal/processor/progress'
      preLoaderRoute: typeof ApiInternalProcessorProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/processor/key-failure': {
      id: '/api/internal/processor/key-failure'
      path: '/api/internal/processor/key-failure'
      fullPath: '/api/internal/processor/key-failure'
      preLoaderRoute: typeof ApiInternalProcessorKeyFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/publishing/$destinationId': {
      id: '/_authed/dashboard/publishing/$destinationId'
      path: '/$destinationId'
      fullPath: '/dashboard/publishing/$destinationId'
      preLoaderRoute: typeof AuthedDashboardPublishingDestinationIdRouteImport
      parentRoute: typeof AuthedDashboardPublishingRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminJobsRoute: typeof AuthedAdminJobsRoute
  AuthedAdminKeysRoute: typeof AuthedAdminKeysRoute
  AuthedAdminSettingsRoute: typeof AuthedAdminSettingsRoute
  AuthedAdminSystemRoute: typeof AuthedAdminSystemRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminJobsRoute: AuthedAdminJobsRoute,
  AuthedAdminKeysRoute: AuthedAdminKeysRoute,
  AuthedAdminSettingsRoute: AuthedAdminSettingsRoute,
  AuthedAdminSystemRoute: AuthedAdminSystemRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedDashboardPublishingRouteChildren {
  AuthedDashboardPublishingDestinationIdRoute: typeof AuthedDashboardPublishingDestinationIdRoute
  AuthedDashboardPublishingIndexRoute: typeof AuthedDashboardPublishingIndexRoute
}

const AuthedDashboardPublishingRouteChildren: AuthedDashboardPublishingRouteChildren =
  {
    AuthedDashboardPublishingDestinationIdRoute:
      AuthedDashboardPublishingDestinationIdRoute,
    AuthedDashboardPublishingIndexRoute: AuthedDashboardPublishingIndexRoute,
  }

const AuthedDashboardPublishingRouteWithChildren =
  AuthedDashboardPublishingRoute._addFileChildren(
    AuthedDashboardPublishingRouteChildren,
  )

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardAnalyticsRoute: typeof AuthedDashboardAnalyticsRoute
  AuthedDashboardBillingRoute: typeof AuthedDashboardBillingRoute
  AuthedDashboardGenerateRoute: typeof AuthedDashboardGenerateRoute
  AuthedDashboardJobsRoute: typeof AuthedDashboardJobsRoute
  AuthedDashboardPublishingRoute: typeof AuthedDashboardPublishingRouteWithChildren
  AuthedDashboardSettingsRoute: typeof AuthedDashboardSettingsRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardAnalyticsRoute: AuthedDashboardAnalyticsRoute,
  AuthedDashboardBillingRoute: AuthedDashboardBillingRoute,
  AuthedDashboardGenerateRoute: AuthedDashboardGenerateRoute,
  AuthedDashboardJobsRoute: AuthedDashboardJobsRoute,
  AuthedDashboardPublishingRoute: AuthedDashboardPublishingRouteWithChildren,
  AuthedDashboardSettingsRoute: AuthedDashboardSettingsRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDispatchQueuedJobsRoute: ApiCronDispatchQueuedJobsRoute,
  ApiCronPurgeExpiringAssetsRoute: ApiCronPurgeExpiringAssetsRoute,
  ApiCronTriggerScheduledJobsRoute: ApiCronTriggerScheduledJobsRoute,
  ApiInternalProcessorKeyFailureRoute: ApiInternalProcessorKeyFailureRoute,
  ApiInternalProcessorProgressRoute: ApiInternalProcessorProgressRoute,
  ApiInternalVideoProcessorAssemblyCompleteRoute:
    ApiInternalVideoProcessorAssemblyCompleteRoute,
  ApiYoutubeOauthCallbackRoute: ApiYoutubeOauthCallbackRoute,
  ApiYoutubeOauthStartRoute: ApiYoutubeOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
