/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPublishingRouteImport } from './routes/dashboard/publishing'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardGenerateRouteImport } from './routes/dashboard/generate'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardPublishingIndexRouteImport } from './routes/dashboard/publishing.index'
import { Route as DashboardPublishingDestinationIdRouteImport } from './routes/dashboard/publishing.$destinationId'
import { Route as ApiCronPurgeExpiringAssetsRouteImport } from './routes/api/cron/purge-expiring-assets'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiYoutubeOauthStartRouteImport } from './routes/api/youtube/oauth/start'
import { Route as ApiYoutubeOauthCallbackRouteImport } from './routes/api/youtube/oauth/callback'
import { Route as ApiInternalWorkerYoutubePublishRouteImport } from './routes/api/internal/worker/youtube-publish'
import { Route as ApiInternalVideoProcessorAssemblyCompleteRouteImport } from './routes/api/internal/video-processor/assembly-complete'
import { Route as ApiInternalWorkerVideoJobsDispatchRouteImport } from './routes/api/internal/worker/video-jobs/dispatch'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPublishingRoute = DashboardPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGenerateRoute = DashboardGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPublishingIndexRoute =
  DashboardPublishingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPublishingRoute,
  } as any)
const DashboardPublishingDestinationIdRoute =
  DashboardPublishingDestinationIdRouteImport.update({
    id: '/$destinationId',
    path: '/$destinationId',
    getParentRoute: () => DashboardPublishingRoute,
  } as any)
const ApiCronPurgeExpiringAssetsRoute =
  ApiCronPurgeExpiringAssetsRouteImport.update({
    id: '/api/cron/purge-expiring-assets',
    path: '/api/cron/purge-expiring-assets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeOauthStartRoute = ApiYoutubeOauthStartRouteImport.update({
  id: '/api/youtube/oauth/start',
  path: '/api/youtube/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeOauthCallbackRoute = ApiYoutubeOauthCallbackRouteImport.update({
  id: '/api/youtube/oauth/callback',
  path: '/api/youtube/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalWorkerYoutubePublishRoute =
  ApiInternalWorkerYoutubePublishRouteImport.update({
    id: '/api/internal/worker/youtube-publish',
    path: '/api/internal/worker/youtube-publish',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalVideoProcessorAssemblyCompleteRoute =
  ApiInternalVideoProcessorAssemblyCompleteRouteImport.update({
    id: '/api/internal/video-processor/assembly-complete',
    path: '/api/internal/video-processor/assembly-complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWorkerVideoJobsDispatchRoute =
  ApiInternalWorkerVideoJobsDispatchRouteImport.update({
    id: '/api/internal/worker/video-jobs/dispatch',
    path: '/api/internal/worker/video-jobs/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/publishing': typeof DashboardPublishingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/purge-expiring-assets': typeof ApiCronPurgeExpiringAssetsRoute
  '/dashboard/publishing/$destinationId': typeof DashboardPublishingDestinationIdRoute
  '/dashboard/publishing/': typeof DashboardPublishingIndexRoute
  '/api/internal/video-processor/assembly-complete': typeof ApiInternalVideoProcessorAssemblyCompleteRoute
  '/api/internal/worker/youtube-publish': typeof ApiInternalWorkerYoutubePublishRoute
  '/api/youtube/oauth/callback': typeof ApiYoutubeOauthCallbackRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
  '/api/internal/worker/video-jobs/dispatch': typeof ApiInternalWorkerVideoJobsDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/purge-expiring-assets': typeof ApiCronPurgeExpiringAssetsRoute
  '/dashboard/publishing/$destinationId': typeof DashboardPublishingDestinationIdRoute
  '/dashboard/publishing': typeof DashboardPublishingIndexRoute
  '/api/internal/video-processor/assembly-complete': typeof ApiInternalVideoProcessorAssemblyCompleteRoute
  '/api/internal/worker/youtube-publish': typeof ApiInternalWorkerYoutubePublishRoute
  '/api/youtube/oauth/callback': typeof ApiYoutubeOauthCallbackRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
  '/api/internal/worker/video-jobs/dispatch': typeof ApiInternalWorkerVideoJobsDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/publishing': typeof DashboardPublishingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/purge-expiring-assets': typeof ApiCronPurgeExpiringAssetsRoute
  '/dashboard/publishing/$destinationId': typeof DashboardPublishingDestinationIdRoute
  '/dashboard/publishing/': typeof DashboardPublishingIndexRoute
  '/api/internal/video-processor/assembly-complete': typeof ApiInternalVideoProcessorAssemblyCompleteRoute
  '/api/internal/worker/youtube-publish': typeof ApiInternalWorkerYoutubePublishRoute
  '/api/youtube/oauth/callback': typeof ApiYoutubeOauthCallbackRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
  '/api/internal/worker/video-jobs/dispatch': typeof ApiInternalWorkerVideoJobsDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/generate'
    | '/dashboard/jobs'
    | '/dashboard/publishing'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/cron/purge-expiring-assets'
    | '/dashboard/publishing/$destinationId'
    | '/dashboard/publishing/'
    | '/api/internal/video-processor/assembly-complete'
    | '/api/internal/worker/youtube-publish'
    | '/api/youtube/oauth/callback'
    | '/api/youtube/oauth/start'
    | '/api/internal/worker/video-jobs/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/generate'
    | '/dashboard/jobs'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/cron/purge-expiring-assets'
    | '/dashboard/publishing/$destinationId'
    | '/dashboard/publishing'
    | '/api/internal/video-processor/assembly-complete'
    | '/api/internal/worker/youtube-publish'
    | '/api/youtube/oauth/callback'
    | '/api/youtube/oauth/start'
    | '/api/internal/worker/video-jobs/dispatch'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/generate'
    | '/dashboard/jobs'
    | '/dashboard/publishing'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/cron/purge-expiring-assets'
    | '/dashboard/publishing/$destinationId'
    | '/dashboard/publishing/'
    | '/api/internal/video-processor/assembly-complete'
    | '/api/internal/worker/youtube-publish'
    | '/api/youtube/oauth/callback'
    | '/api/youtube/oauth/start'
    | '/api/internal/worker/video-jobs/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronPurgeExpiringAssetsRoute: typeof ApiCronPurgeExpiringAssetsRoute
  ApiInternalVideoProcessorAssemblyCompleteRoute: typeof ApiInternalVideoProcessorAssemblyCompleteRoute
  ApiInternalWorkerYoutubePublishRoute: typeof ApiInternalWorkerYoutubePublishRoute
  ApiYoutubeOauthCallbackRoute: typeof ApiYoutubeOauthCallbackRoute
  ApiYoutubeOauthStartRoute: typeof ApiYoutubeOauthStartRoute
  ApiInternalWorkerVideoJobsDispatchRoute: typeof ApiInternalWorkerVideoJobsDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/publishing': {
      id: '/dashboard/publishing'
      path: '/publishing'
      fullPath: '/dashboard/publishing'
      preLoaderRoute: typeof DashboardPublishingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/generate': {
      id: '/dashboard/generate'
      path: '/generate'
      fullPath: '/dashboard/generate'
      preLoaderRoute: typeof DashboardGenerateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/publishing/': {
      id: '/dashboard/publishing/'
      path: '/'
      fullPath: '/dashboard/publishing/'
      preLoaderRoute: typeof DashboardPublishingIndexRouteImport
      parentRoute: typeof DashboardPublishingRoute
    }
    '/dashboard/publishing/$destinationId': {
      id: '/dashboard/publishing/$destinationId'
      path: '/$destinationId'
      fullPath: '/dashboard/publishing/$destinationId'
      preLoaderRoute: typeof DashboardPublishingDestinationIdRouteImport
      parentRoute: typeof DashboardPublishingRoute
    }
    '/api/cron/purge-expiring-assets': {
      id: '/api/cron/purge-expiring-assets'
      path: '/api/cron/purge-expiring-assets'
      fullPath: '/api/cron/purge-expiring-assets'
      preLoaderRoute: typeof ApiCronPurgeExpiringAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/oauth/start': {
      id: '/api/youtube/oauth/start'
      path: '/api/youtube/oauth/start'
      fullPath: '/api/youtube/oauth/start'
      preLoaderRoute: typeof ApiYoutubeOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/oauth/callback': {
      id: '/api/youtube/oauth/callback'
      path: '/api/youtube/oauth/callback'
      fullPath: '/api/youtube/oauth/callback'
      preLoaderRoute: typeof ApiYoutubeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/worker/youtube-publish': {
      id: '/api/internal/worker/youtube-publish'
      path: '/api/internal/worker/youtube-publish'
      fullPath: '/api/internal/worker/youtube-publish'
      preLoaderRoute: typeof ApiInternalWorkerYoutubePublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/video-processor/assembly-complete': {
      id: '/api/internal/video-processor/assembly-complete'
      path: '/api/internal/video-processor/assembly-complete'
      fullPath: '/api/internal/video-processor/assembly-complete'
      preLoaderRoute: typeof ApiInternalVideoProcessorAssemblyCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/worker/video-jobs/dispatch': {
      id: '/api/internal/worker/video-jobs/dispatch'
      path: '/api/internal/worker/video-jobs/dispatch'
      fullPath: '/api/internal/worker/video-jobs/dispatch'
      preLoaderRoute: typeof ApiInternalWorkerVideoJobsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardPublishingRouteChildren {
  DashboardPublishingDestinationIdRoute: typeof DashboardPublishingDestinationIdRoute
  DashboardPublishingIndexRoute: typeof DashboardPublishingIndexRoute
}

const DashboardPublishingRouteChildren: DashboardPublishingRouteChildren = {
  DashboardPublishingDestinationIdRoute: DashboardPublishingDestinationIdRoute,
  DashboardPublishingIndexRoute: DashboardPublishingIndexRoute,
}

const DashboardPublishingRouteWithChildren =
  DashboardPublishingRoute._addFileChildren(DashboardPublishingRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardGenerateRoute: typeof DashboardGenerateRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardPublishingRoute: typeof DashboardPublishingRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardGenerateRoute: DashboardGenerateRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardPublishingRoute: DashboardPublishingRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronPurgeExpiringAssetsRoute: ApiCronPurgeExpiringAssetsRoute,
  ApiInternalVideoProcessorAssemblyCompleteRoute:
    ApiInternalVideoProcessorAssemblyCompleteRoute,
  ApiInternalWorkerYoutubePublishRoute: ApiInternalWorkerYoutubePublishRoute,
  ApiYoutubeOauthCallbackRoute: ApiYoutubeOauthCallbackRoute,
  ApiYoutubeOauthStartRoute: ApiYoutubeOauthStartRoute,
  ApiInternalWorkerVideoJobsDispatchRoute:
    ApiInternalWorkerVideoJobsDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
