/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPublishingRouteImport } from './routes/dashboard/publishing'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardGenerateRouteImport } from './routes/dashboard/generate'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardPublishingDestinationIdRouteImport } from './routes/dashboard/publishing.$destinationId'
import { Route as ApiCronPolarUsageSyncRouteImport } from './routes/api/cron/polar-usage-sync'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInternalWorkerPolarUsageSyncDrainRouteImport } from './routes/api/internal/worker/polar-usage-sync/drain'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPublishingRoute = DashboardPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGenerateRoute = DashboardGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPublishingDestinationIdRoute =
  DashboardPublishingDestinationIdRouteImport.update({
    id: '/$destinationId',
    path: '/$destinationId',
    getParentRoute: () => DashboardPublishingRoute,
  } as any)
const ApiCronPolarUsageSyncRoute = ApiCronPolarUsageSyncRouteImport.update({
  id: '/api/cron/polar-usage-sync',
  path: '/api/cron/polar-usage-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalWorkerPolarUsageSyncDrainRoute =
  ApiInternalWorkerPolarUsageSyncDrainRouteImport.update({
    id: '/api/internal/worker/polar-usage-sync/drain',
    path: '/api/internal/worker/polar-usage-sync/drain',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/publishing': typeof DashboardPublishingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/polar-usage-sync': typeof ApiCronPolarUsageSyncRoute
  '/dashboard/publishing/$destinationId': typeof DashboardPublishingDestinationIdRoute
  '/api/internal/worker/polar-usage-sync/drain': typeof ApiInternalWorkerPolarUsageSyncDrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/publishing': typeof DashboardPublishingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/polar-usage-sync': typeof ApiCronPolarUsageSyncRoute
  '/dashboard/publishing/$destinationId': typeof DashboardPublishingDestinationIdRoute
  '/api/internal/worker/polar-usage-sync/drain': typeof ApiInternalWorkerPolarUsageSyncDrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/publishing': typeof DashboardPublishingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/polar-usage-sync': typeof ApiCronPolarUsageSyncRoute
  '/dashboard/publishing/$destinationId': typeof DashboardPublishingDestinationIdRoute
  '/api/internal/worker/polar-usage-sync/drain': typeof ApiInternalWorkerPolarUsageSyncDrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/generate'
    | '/dashboard/jobs'
    | '/dashboard/publishing'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/cron/polar-usage-sync'
    | '/dashboard/publishing/$destinationId'
    | '/api/internal/worker/polar-usage-sync/drain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/generate'
    | '/dashboard/jobs'
    | '/dashboard/publishing'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/cron/polar-usage-sync'
    | '/dashboard/publishing/$destinationId'
    | '/api/internal/worker/polar-usage-sync/drain'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/generate'
    | '/dashboard/jobs'
    | '/dashboard/publishing'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/cron/polar-usage-sync'
    | '/dashboard/publishing/$destinationId'
    | '/api/internal/worker/polar-usage-sync/drain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronPolarUsageSyncRoute: typeof ApiCronPolarUsageSyncRoute
  ApiInternalWorkerPolarUsageSyncDrainRoute: typeof ApiInternalWorkerPolarUsageSyncDrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/publishing': {
      id: '/dashboard/publishing'
      path: '/publishing'
      fullPath: '/dashboard/publishing'
      preLoaderRoute: typeof DashboardPublishingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/generate': {
      id: '/dashboard/generate'
      path: '/generate'
      fullPath: '/dashboard/generate'
      preLoaderRoute: typeof DashboardGenerateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/publishing/$destinationId': {
      id: '/dashboard/publishing/$destinationId'
      path: '/$destinationId'
      fullPath: '/dashboard/publishing/$destinationId'
      preLoaderRoute: typeof DashboardPublishingDestinationIdRouteImport
      parentRoute: typeof DashboardPublishingRoute
    }
    '/api/cron/polar-usage-sync': {
      id: '/api/cron/polar-usage-sync'
      path: '/api/cron/polar-usage-sync'
      fullPath: '/api/cron/polar-usage-sync'
      preLoaderRoute: typeof ApiCronPolarUsageSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/worker/polar-usage-sync/drain': {
      id: '/api/internal/worker/polar-usage-sync/drain'
      path: '/api/internal/worker/polar-usage-sync/drain'
      fullPath: '/api/internal/worker/polar-usage-sync/drain'
      preLoaderRoute: typeof ApiInternalWorkerPolarUsageSyncDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardPublishingRouteChildren {
  DashboardPublishingDestinationIdRoute: typeof DashboardPublishingDestinationIdRoute
}

const DashboardPublishingRouteChildren: DashboardPublishingRouteChildren = {
  DashboardPublishingDestinationIdRoute: DashboardPublishingDestinationIdRoute,
}

const DashboardPublishingRouteWithChildren =
  DashboardPublishingRoute._addFileChildren(DashboardPublishingRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardGenerateRoute: typeof DashboardGenerateRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardPublishingRoute: typeof DashboardPublishingRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardGenerateRoute: DashboardGenerateRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardPublishingRoute: DashboardPublishingRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronPolarUsageSyncRoute: ApiCronPolarUsageSyncRoute,
  ApiInternalWorkerPolarUsageSyncDrainRoute:
    ApiInternalWorkerPolarUsageSyncDrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
